/**
 * Configurações centralizadas de SEO
 * Atualize SITE_URL ao fazer deploy (ex: https://fabriciosantos.dev)
 */
export const siteConfig = {
  name: "Fabrício Santos",
  title: "Fabrício Santos | Programador/Desenvolvedor Full-Stack",
  description:
    "Programador/desenvolvedor full-stack em Recife (PE), atuando com Health Tech, Computer Vision e IA aplicada. Mais de 2 anos desenvolvendo aplicações web e mobile. Especialista em React, NestJS, Next.js e React Native.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://fabriciosantos.dev.br",
  locale: "pt_BR",
  keywords: [
    // Variações de "programador"
    "programador",
    "Programador",
    "programadora",
    "Programadora",
    "programadores",
    "Programadores",
    "programadoras",
    "Programadoras",
    "programação",
    "Programação",
    "programacao",
    "Programacao",
    "programador full-stack",
    "Programador full-stack",
    "programador de software",
    "Programador de software",
    "programador web",
    "Programador web",
    "programador React",
    "Programador React",
    "programador Next.js",
    "Programador Next.js",
    "programador JavaScript",
    "Programador JavaScript",
    "programador TypeScript",
    "Programador TypeScript",
    "programador Recife",
    "Programador Recife",
    // Programador + áreas (Mobile/Web/Front/Back/Site/Aplicativo)
    "programador mobile",
    "Programador mobile",
    "programador Mobile",
    "Programador Mobile",
    "programador de aplicativo",
    "Programador de aplicativo",
    "programador de aplicativos",
    "Programador de aplicativos",
    "programador de aplicativo mobile",
    "Programador de aplicativo mobile",
    "programador de aplicativos mobile",
    "Programador de aplicativos mobile",
    "programador web",
    "Programador web",
    "programador Web",
    "Programador Web",
    "programador de site",
    "Programador de site",
    "programador de sites",
    "Programador de sites",
    "programador front-end",
    "Programador front-end",
    "programador frontend",
    "Programador frontend",
    "programador back-end",
    "Programador back-end",
    "programador backend",
    "Programador backend",
    // Variações de "desenvolvedor"
    "desenvolvedor",
    "Desenvolvedor",
    "desenvolvedora",
    "Desenvolvedora",
    "desenvolvedores",
    "Desenvolvedores",
    "desenvolvedoras",
    "Desenvolvedoras",
    "desenvolvimento",
    "Desenvolvimento",
    "desenvolvimento de software",
    "Desenvolvimento de software",
    "desenvolvedor full-stack",
    "Desenvolvedor full-stack",
    "desenvolvedor de software",
    "Desenvolvedor de software",
    "desenvolvedor web",
    "Desenvolvedor web",
    "desenvolvedor React",
    "Desenvolvedor React",
    "desenvolvedor React Native",
    "Desenvolvedor React Native",
    "desenvolvedor TypeScript",
    "Desenvolvedor TypeScript",
    "desenvolvedor Recife",
    "Desenvolvedor Recife",
    // Desenvolvedor + áreas (Mobile/Web/Front/Back/Site/Aplicativo)
    "desenvolvedor mobile",
    "Desenvolvedor mobile",
    "desenvolvedor Mobile",
    "Desenvolvedor Mobile",
    "desenvolvedor de aplicativo",
    "Desenvolvedor de aplicativo",
    "desenvolvedor de aplicativos",
    "Desenvolvedor de aplicativos",
    "desenvolvedor de aplicativo mobile",
    "Desenvolvedor de aplicativo mobile",
    "desenvolvedor de aplicativos mobile",
    "Desenvolvedor de aplicativos mobile",
    "desenvolvedor web",
    "Desenvolvedor web",
    "desenvolvedor Web",
    "Desenvolvedor Web",
    "desenvolvedor de site",
    "Desenvolvedor de site",
    "desenvolvedor de sites",
    "Desenvolvedor de sites",
    "desenvolvedor front-end",
    "Desenvolvedor front-end",
    "desenvolvedor frontend",
    "Desenvolvedor frontend",
    "desenvolvedor back-end",
    "Desenvolvedor back-end",
    "desenvolvedor backend",
    "Desenvolvedor backend",
    // Variações com e sem acento em termos relacionados
    "programacao web",
    "Programacao web",
    "programação web",
    "Programação web",
    "inteligência artificial",
    "Inteligência artificial",
    "inteligencia artificial",
    "Inteligencia artificial",
    // Combinações com nome
    "programador Fabricio Santos",
    "Fabricio Santos programador",
    "Programador Chã de Alegria",
    "Programador Rotas4Me",
    "Rotas4Me",
    "Programador Glória do Goitá",
    "Programador Vitória de Santo Antão",
    "Programador Vitória",
    "Health Tech",
    "Computer Vision",
    "desenvolvedor Recife",
    "inteligênica artifical",
    "Fabricio Santos",
    "Fabrício Santos",
    "NestJS",
    "Next.js",
    // Combinações com cidades (programador/desenvolvedor + cidades)
    // Chã de Alegria (e variações)
    "programador Chã de Alegria",
    "Programador Chã de Alegria",
    "desenvolvedor Chã de Alegria",
    "Desenvolvedor Chã de Alegria",
    "programador Cha de Alegria",
    "Programador Cha de Alegria",
    "desenvolvedor Cha de Alegria",
    "Desenvolvedor Cha de Alegria",
    // Vitória de Santo Antão
    "programador Vitória de Santo Antão",
    "Programador Vitória de Santo Antão",
    "desenvolvedor Vitória de Santo Antão",
    "Desenvolvedor Vitória de Santo Antão",
    "programador Vitoria de Santo Antao",
    "Programador Vitoria de Santo Antao",
    "desenvolvedor Vitoria de Santo Antao",
    "Desenvolvedor Vitoria de Santo Antao",
    // Vitória
    "programador Vitória",
    "Programador Vitória",
    "desenvolvedor Vitória",
    "Desenvolvedor Vitória",
    "programador Vitoria",
    "Programador Vitoria",
    "desenvolvedor Vitoria",
    "Desenvolvedor Vitoria",
    // Paudalho
    "programador Paudalho",
    "Programador Paudalho",
    "desenvolvedor Paudalho",
    "Desenvolvedor Paudalho",
    // Recife (já existem, mantidos acima) – reforço
    "programador Recife PE",
    "desenvolvedor Recife PE",
    // Glória do Goitá
    "programador Glória do Goitá",
    "Programador Glória do Goitá",
    "desenvolvedor Glória do Goitá",
    "Desenvolvedor Glória do Goitá",
    "programador Gloria do Goita",
    "Programador Gloria do Goita",
    "desenvolvedor Gloria do Goita",
    "Desenvolvedor Gloria do Goita",
    // Glória
    "programador Glória",
    "Programador Glória",
    "desenvolvedor Glória",
    "Desenvolvedor Glória",
    "programador Gloria",
    "Programador Gloria",
    "desenvolvedor Gloria",
    "Desenvolvedor Gloria",
    // Outras cidades da Região Metropolitana do Recife
    // Olinda
    "programador Olinda",
    "Programador Olinda",
    "desenvolvedor Olinda",
    "Desenvolvedor Olinda",
    // Jaboatão dos Guararapes
    "programador Jaboatão dos Guararapes",
    "Programador Jaboatão dos Guararapes",
    "desenvolvedor Jaboatão dos Guararapes",
    "Desenvolvedor Jaboatão dos Guararapes",
    "programador Jaboatao dos Guararapes",
    "Programador Jaboatao dos Guararapes",
    "desenvolvedor Jaboatao dos Guararapes",
    "Desenvolvedor Jaboatao dos Guararapes",
    // Camaragibe
    "programador Camaragibe",
    "Programador Camaragibe",
    "desenvolvedor Camaragibe",
    "Desenvolvedor Camaragibe",
    // Paulista
    "programador Paulista",
    "Programador Paulista",
    "desenvolvedor Paulista",
    "Desenvolvedor Paulista",
    // Abreu e Lima
    "programador Abreu e Lima",
    "Programador Abreu e Lima",
    "desenvolvedor Abreu e Lima",
    "Desenvolvedor Abreu e Lima",
    // Igarassu
    "programador Igarassu",
    "Programador Igarassu",
    "desenvolvedor Igarassu",
    "Desenvolvedor Igarassu",
    // São Lourenço da Mata
    "programador São Lourenço da Mata",
    "Programador São Lourenço da Mata",
    "desenvolvedor São Lourenço da Mata",
    "Desenvolvedor São Lourenço da Mata",
    "programador Sao Lourenco da Mata",
    "Programador Sao Lourenco da Mata",
    "desenvolvedor Sao Lourenco da Mata",
    "Desenvolvedor Sao Lourenco da Mata",
    // Moreno
    "programador Moreno",
    "Programador Moreno",
    "desenvolvedor Moreno",
    "Desenvolvedor Moreno",
    // Cabo de Santo Agostinho
    "programador Cabo de Santo Agostinho",
    "Programador Cabo de Santo Agostinho",
    "desenvolvedor Cabo de Santo Agostinho",
    "Desenvolvedor Cabo de Santo Agostinho",
    // Itapissuma
    "programador Itapissuma",
    "Programador Itapissuma",
    "desenvolvedor Itapissuma",
    "Desenvolvedor Itapissuma",
    // Araçoiaba
    "programador Araçoiaba",
    "Programador Araçoiaba",
    "desenvolvedor Araçoiaba",
    "Desenvolvedor Araçoiaba",
    "programador Aracoiaba",
    "Programador Aracoiaba",
    "desenvolvedor Aracoiaba",
    "Desenvolvedor Aracoiaba",
  ],
  author: "Fabrício Santos",
  openGraph: {
    type: "website",
    locale: "pt_BR",
  },
  twitter: {
    card: "summary_large_image",
    creator: "@fabriciosantos",
  },
} as const;
